# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'kt-invent-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kt-invent-ios
    pod 'Alamofire'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'Charts'
    pod 'IQKeyboardManagerSwift'
    pod 'BWWalkthrough'
    pod 'DZNEmptyDataSet'
    pod 'SwiftDate'
end
